In [1]:
import pandas as pd

X_train = pd.read_csv("../data/X_train.csv")

y_train = pd.read_csv(
    "../data/y_train.csv"
).squeeze()

In [2]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

In [3]:
from xgboost import XGBRegressor

from src.evaluate import rmse_cv

In [4]:
xgb_model = XGBRegressor(
    n_estimators=1000,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

xgb_rmse = rmse_cv(
    xgb_model,
    X_train,
    y_train
).mean()

print(
    f"XGBoost RMSE: {xgb_rmse:.5f}"
)

XGBoost RMSE: 0.12078


In [5]:
X_test = pd.read_csv(
    "../data/X_test.csv"
)

test = pd.read_csv(
    "../data/test.csv"
)

print(X_test.shape)
print(test.shape)

(1459, 318)
(1459, 80)


In [6]:
xgb_model.fit(
    X_train,
    y_train
)

print("XGB 訓練完成")

XGB 訓練完成


In [7]:
xgb_pred_log = xgb_model.predict(
    X_test
)

print(xgb_pred_log[:5])

[11.750546 11.969568 12.116489 12.161827 12.12955 ]


In [8]:
import numpy as np

xgb_pred = np.expm1(
    xgb_pred_log
)

print(xgb_pred[:5])

[126821.84 157875.48 182861.44 191342.8  185265.39]


In [9]:
submission = pd.DataFrame({
    "Id": test["Id"],
    "SalePrice": xgb_pred
})

submission.head()

,Id,SalePrice
0,1461,126821.843750
1,1462,157875.484375
2,1463,182861.437500
3,1464,191342.796875
4,1465,185265.390625


In [10]:
submission.to_csv(
    "../submissions/xgb_submission.csv",
    index=False
)

print("XGB Submission 已建立")

XGB Submission 已建立


In [11]:
# XGBoost v2

xgb_model_v2 = XGBRegressor(
    n_estimators=3000,
    learning_rate=0.01,
    max_depth=3,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_rmse_v2 = rmse_cv(
    xgb_model_v2,
    X_train,
    y_train
).mean()

print(
    f"XGB v2 RMSE: {xgb_rmse_v2:.5f}"
)

XGB v2 RMSE: 0.11495


In [12]:
xgb_model_v2.fit(
    X_train,
    y_train
)

print("XGB v2 訓練完成")

XGB v2 訓練完成


In [13]:
xgb_pred_log_v2 = xgb_model_v2.predict(
    X_test
)

print(xgb_pred_log_v2[:5])

[11.726706 12.00516  12.12229  12.174093 12.116671]


In [14]:
xgb_pred_v2 = np.expm1(
    xgb_pred_log_v2
)

print(xgb_pred_v2[:5])

[123834.03 163595.83 183925.16 193704.31 182894.56]


In [15]:
submission_v2 = pd.DataFrame({
    "Id": test["Id"],
    "SalePrice": xgb_pred_v2
})

submission_v2.head()

,Id,SalePrice
0,1461,123834.031250
1,1462,163595.828125
2,1463,183925.156250
3,1464,193704.312500
4,1465,182894.562500


In [16]:
submission_v2.to_csv(
    "../submissions/xgb_v2_submission.csv",
    index=False
)

print("XGB v2 Submission 已建立")

XGB v2 Submission 已建立


In [17]:
# XGBoost v3

xgb_model_v3 = XGBRegressor(
    n_estimators=5000,
    learning_rate=0.01,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_rmse_v3 = rmse_cv(
    xgb_model_v3,
    X_train,
    y_train
).mean()

print(
    f"XGB v3 RMSE: {xgb_rmse_v3:.5f}"
)

XGB v3 RMSE: 0.11639


In [ ]:
xgb_model_v4 = XGBRegressor(
    n_estimators=2000,
    learning_rate=0.03,
    max_depth=3,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)